services:
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6374:6379"
    networks:
      - app_network
  
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network: