/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as authenticatedLayout2Import } from './routes/(authenticated)/_layout-2'
import { Route as authenticatedLayoutImport } from './routes/(authenticated)/_layout'
import { Route as authenticatedLayout2IndexImport } from './routes/(authenticated)/_layout-2/index'
import { Route as authenticatedLayoutSettingsProfileImport } from './routes/(authenticated)/_layout/settings/profile'

// Create Virtual Routes

const authenticatedImport = createFileRoute('/(authenticated)')()

// Create/Update Routes

const authenticatedRoute = authenticatedImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const authenticatedLayout2Route = authenticatedLayout2Import.update({
  id: '/_layout-2',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedLayoutRoute = authenticatedLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => authenticatedRoute,
} as any)

const authenticatedLayout2IndexRoute = authenticatedLayout2IndexImport.update({
  path: '/',
  getParentRoute: () => authenticatedLayout2Route,
} as any)

const authenticatedLayoutSettingsProfileRoute =
  authenticatedLayoutSettingsProfileImport.update({
    path: '/settings/profile',
    getParentRoute: () => authenticatedLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(authenticated)': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedImport
      parentRoute: typeof rootRoute
    }
    '/(authenticated)/_layout': {
      id: '/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedLayoutImport
      parentRoute: typeof authenticatedRoute
    }
    '/(authenticated)/_layout-2': {
      id: '/_layout-2'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedLayout2Import
      parentRoute: typeof authenticatedImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/(authenticated)/_layout-2/': {
      id: '/_layout-2/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedLayout2IndexImport
      parentRoute: typeof authenticatedLayout2Import
    }
    '/(authenticated)/_layout/settings/profile': {
      id: '/_layout/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof authenticatedLayoutSettingsProfileImport
      parentRoute: typeof authenticatedLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  authenticatedRoute: authenticatedRoute.addChildren({
    authenticatedLayoutRoute: authenticatedLayoutRoute.addChildren({
      authenticatedLayoutSettingsProfileRoute,
    }),
    authenticatedLayout2Route: authenticatedLayout2Route.addChildren({
      authenticatedLayout2IndexRoute,
    }),
  }),
  AuthRegisterRoute,
  AuthIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/register",
        "/auth/"
      ]
    },
    "/": {
      "filePath": "(authenticated)",
      "children": [
        "/_layout",
        "/_layout-2"
      ]
    },
    "/_layout": {
      "filePath": "(authenticated)/_layout.tsx",
      "parent": "/",
      "children": [
        "/_layout/settings/profile"
      ]
    },
    "/_layout-2": {
      "filePath": "(authenticated)/_layout-2.tsx",
      "parent": "/",
      "children": [
        "/_layout-2/"
      ]
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/_layout-2/": {
      "filePath": "(authenticated)/_layout-2/index.tsx",
      "parent": "/_layout-2"
    },
    "/_layout/settings/profile": {
      "filePath": "(authenticated)/_layout/settings/profile.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
